sudo: false

language: node_js
node_js:
  - 10

install:
  # Tell npm to ignore package-lock.json to avoid making local file
  # changes that would dirty the git workspace.
  - npm config set package-lock false
  - npm install
